### ISSUE TITLE
工程移植到QT5.10.1时出现编译问题

### ISSUE THREAD

**Issue by QuintonZhang** [596142041/CANBootloader-Qt#1]
工程移植到QT5.10.1时出现编译问题，问题应当是库文件加载问题，描述如下，麻烦回应，不胜感谢：

..\..\CANBootloaderQtmaster\source\mainwindow.cpp(1875): warning C4309: “初始化”: 截断常量值
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:debug\CANBootloader.exe @C:\Users\ADMINI~1\AppData\Local\Temp\CANBootloader.exe.5628.4945.jom
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
mainwindow.obj : error LNK2019: 
C:\Users\Administrator\Desktop\CANBootloaderQtmaster\project\lib\win32\ControlCAN.lib : warning LNK4272:
debug\CANBootloader.exe : fatal error LNK1120: 10 
jom: C:\Users\Administrator\Desktop\CANBootloader-Qt-master\build-CAN_Bootloader-Desktop_Qt_5_10_1_MSVC2015_64bit-Debug\Makefile.Debug [debug\CANBootloader.exe] Error 1120
jom: C:\Users\Administrator\Desktop\CANBootloader-Qt-master\build-CAN_Bootloader-Desktop_Qt_5_10_1_MSVC2015_64bit-Debug\Makefile [debug] Error 2
17:04:01: 进程"D:\Qt\Qt5.10.1\Tools\QtCreator\bin\jom.exe"退出，退出代码 2 。
Error while building/deploying project CAN_Bootloader (kit: Desktop Qt 5.10.1 MSVC2015 64bit)
The kit Desktop Qt 5.10.1 MSVC2015 64bit has configuration issues which might be the root cause for this problem.
When executing step "Make"
17:04:01: Elapsed time: 00:05.

**Comment by 596142041** [comment]
你好!我之前使用QT5.10.1也是同样报故障,编译器使用的MinGW,后面我是一直使用的是QT5.10.0的版本进行的编译.你在编译之前将这文件CAN_Bootloader.pro.user删除看一下.



皇甫仁和
 
发件人： QuintonZhang
发送时间： 2018-06-11 17:14
收件人： 596142041/CANBootloader-Qt
抄送： Subscribed
主题： [596142041/CANBootloader-Qt] 工程移植到QT5.10.1时出现编译问题 (#1)
工程移植到QT5.10.1时出现编译问题，问题应当是库文件加载问题，描述如下，麻烦回应，不胜感谢：
....\CANBootloaderQtmaster\source\mainwindow.cpp(1875): warning C4309: “初始化”: 截断常量值
link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='' processorArchitecture=''" /MANIFEST:embed /OUT:debug\CANBootloader.exe @c:\Users\ADMINI~1\AppData\Local\Temp\CANBootloader.exe.5628.4945.jom
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
mainwindow.obj : error LNK2019:
C:\Users\Administrator\Desktop\CANBootloaderQtmaster\project\lib\win32\ControlCAN.lib : warning LNK4272:
debug\CANBootloader.exe : fatal error LNK1120: 10
jom: C:\Users\Administrator\Desktop\CANBootloader-Qt-master\build-CAN_Bootloader-Desktop_Qt_5_10_1_MSVC2015_64bit-Debug\Makefile.Debug [debug\CANBootloader.exe] Error 1120
jom: C:\Users\Administrator\Desktop\CANBootloader-Qt-master\build-CAN_Bootloader-Desktop_Qt_5_10_1_MSVC2015_64bit-Debug\Makefile [debug] Error 2
17:04:01: 进程"D:\Qt\Qt5.10.1\Tools\QtCreator\bin\jom.exe"退出，退出代码 2 。
Error while building/deploying project CAN_Bootloader (kit: Desktop Qt 5.10.1 MSVC2015 64bit)
The kit Desktop Qt 5.10.1 MSVC2015 64bit has configuration issues which might be the root cause for this problem.
When executing step "Make"
17:04:01: Elapsed time: 00:05.

**Comment by 596142041** [comment]
具体什么原因,我不清楚,没有去查找

**Comment by QuintonZhang** [comment]
软件使用5.10.0MinGW编译已经成功， 十分感谢1
